"""Format summary output as Markdown."""


def format_output(summarize_output: dict, parse_output: dict) -> str:
    why = summarize_output.get("why_inferred") or "_Not enough context to infer._"
    files = "\n".join(f"- `{f}`" for f in summarize_output.get("files_touched", []))
    return f"""# Session Summary
_Generated by Spotlight_

## What Changed
{summarize_output["what_changed"]}

## Why (Inferred)
{why}

## Files Touched
{files}

## Stats
- Lines added: {parse_output["lines_added"]}
- Lines removed: {parse_output["lines_removed"]}
- Files changed: {len(parse_output["files_changed"])}
"""
