"""Format summary output as Markdown."""


def _render_list(items: list, empty_msg: str) -> str:
    if not items:
        return empty_msg
    return "\n".join(f"- {item}" for item in items)


def format_output(summarize_output: dict, parse_output: dict) -> str:
    return f"""# Session Summary
_Generated by Spotlight_

## Summary
{summarize_output["summary"]}

## Changes
{_render_list(summarize_output["changes"], "")}

## Risks
{_render_list(summarize_output.get("risks", []), "_No obvious risks identified._")}

## Next Actions
{_render_list(summarize_output.get("next_actions", []), "_None at this time._")}

## Questions
{_render_list(summarize_output.get("questions", []), "_None._")}

---
_Stats: {parse_output["lines_added"]}++ / {parse_output["lines_removed"]}-- across {len(parse_output["files_changed"])} file(s)_
"""
