"""Format summary output as Markdown."""

from datetime import datetime


def _render_list(items: list, empty_msg: str) -> str:
    if not items:
        return empty_msg
    return "\n".join(f"- {item}" for item in items)


def format_output(summarize_output: dict, parse_output: dict) -> str:
    return f"""# Session Summary
_Generated by Spotlight_

## Summary
{summarize_output["summary"]}

## Changes
{_render_list(summarize_output["changes"], "")}

## Risks
{_render_list(summarize_output.get("risks", []), "_No obvious risks identified._")}

## Next Actions
{_render_list(summarize_output.get("next_actions", []), "_None at this time._")}

## Questions
{_render_list(summarize_output.get("questions", []), "_None._")}

---
_Stats: {parse_output["lines_added"]}++ / {parse_output["lines_removed"]}-- across {len(parse_output["files_changed"])} file(s)_
"""


_SEVERITY_EMOJI = {"critical": "🔴", "warn": "⚠️", "info": "ℹ️"}

def _format_risk_flags(risk_output: dict) -> str:
    if not risk_output or not risk_output.get("flags"):
        return "_No significant risks identified._"
    return "\n".join(f"- {_SEVERITY_EMOJI.get((f.get('severity', 'info') or 'info').lower(), 'ℹ️')} **[{f.get('severity', 'info')}] {f.get('category', '')}**：{f.get('detail', '')}" for f in risk_output["flags"])


def format_pr(
    summarize_output: dict,
    parse_output: dict,
    risk_output: dict = None,
) -> str:
    """輸出 GitHub PR 描述格式的 Markdown 字串。"""
    s = summarize_output
    changes = "\n".join(f"- {c}" for c in s.get("changes", []))
    checklist = "\n".join(f"- [ ] {a}" for a in s.get("next_actions", []))
    questions = s.get("questions", [])
    questions_str = "\n".join(f"- {q}" for q in questions) if questions else "_None._"
    return "\n\n".join([
        f"# [feat] {s['summary'][:60].rstrip('。，！？、；：.,;:!?')}",
        f"## Summary\n{s['summary']}",
        f"## Changes\n{changes}",
        f"## Risk Flags 🚩\n{_format_risk_flags(risk_output)}",
        f"## Reviewer Checklist ✅\n> 請 Reviewer 在 approve 前確認以下項目：\n\n{checklist}\n- [ ] 確認 CI 測試全部通過",
        f"## Open Questions ❓\n{questions_str}",
        f"---\n_Generated by Spotlight | {len(parse_output.get('files_written', []))} file(s) modified_",
    ])


def format_handoff(
    summarize_output: dict,
    parse_output: dict,
    risk_output: dict = None,
) -> str:
    """輸出適合貼入 Notion/HackMD 的交接備忘錄格式。"""
    s = summarize_output
    changes = "\n".join(f"| 完成項 | {c} |" for c in s.get("changes", []))
    risks = s.get("risks", [])
    if not risks and risk_output and risk_output.get("flags"):
        crit = [f for f in risk_output["flags"] if f.get("severity", "").lower() == "critical"]
        if crit:
            risks = [f"{_SEVERITY_EMOJI.get((f.get('severity') or '').lower(), 'ℹ️')} **[{f.get('severity')}] {f.get('category')}**：{f.get('detail')}" for f in crit]
    risk_lines = "\n".join(f"- {r}" for r in risks) if risks else "目前沒有已知風險。"
    todos = "\n".join(f"- [ ] {a}" for a in s.get("next_actions", []))
    questions = s.get("questions", [])
    questions_str = "\n".join(f"- {q}" for q in questions) if questions else "無待釐清問題。"
    files = "\n".join(f"- `{f}`" for f in s.get("files_touched", []))
    return "\n\n".join([
        "# 工作交接備忘錄",
        f"> 📅 建立時間：{datetime.utcnow().strftime('%Y-%m-%d')}\n> 🤖 資料來源：Spotlight（AI Coding Session 分析）",
        "---",
        f"## 🎯 這次在做什麼\n\n{s['summary']}",
        "---",
        f"## ✅ 已完成的事情\n\n| 項目 | 說明 |\n|------|------|\n{changes}",
        "---",
        f"## ⚠️ 需要注意的風險\n\n{risk_lines}",
        "---",
        f"## 📋 待辦清單（接手人請確認）\n\n{todos}",
        "---",
        f"## ❓ 未解決的問題\n\n{questions_str}",
        "---",
        f"## 📁 涉及的檔案\n\n{files}",
        "---",
        "_此文件由 Spotlight 自動生成，建議人工審閱後再交接。_",
    ])
